<?php
return [
//    'adminEmail' => 'admin@example.com',
    'adminEmail' => EMAIL_ADMIN,
    'supportEmail' => 'it@rfprt.ru',
//    'senderEmail' => 'noreply@rfprt.ru',
    'senderEmail' => 'it@rfprt.ru',
    'senderName' => 'postmaster',
    'user.passwordResetTokenExpire' => 3600,
	'myAppName' => '"Выпуск 81"',
	'language' => 'ru-Ru',
	'checkPassword' => CHECK_FROM_SMS,
//	'checkPassword' => CHECK_FROM_EMAIL,
	'lenGallery' => 7,
	'imgExt' => 'png, jpg, jpeg',
	'imgStoreMin' => 'upload/store',
	'imgCacheMin' => 'upload/cache',
	'imgStore' => 'upload/store/',
	'imgCache' => 'upload/cache/',
];
